services:
  db:
    container_name: DomofonEmualtorDataBase
    image: postgres:16.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: my_pass
      POSTGRES_DB: domofon
      PGDATA: /data/postgres
    volumes:
      - ./postgres-data:/data/postgres
    ports:
      - "5432:5432"

  mqtt:
    image: eclipse-mosquitto:2
    ports:
      - "1883:1883"
      - "8083:8083"
    volumes:
      - ./mosquitto.conf:/server/mqtt/config/mqtt.conf
    command: /usr/sbin/mosquitto -c /server/mqtt/config/mqtt.conf
    restart: unless-stopped

  redis:
    image: redis:7.2
    container_name: domofon-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data

  server:
    image: golang:1.24.4
    working_dir: /app
    volumes:
      - ./:/app
    command: sh -c "go run ./server/cmd/main.go"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=my_pass
      - DB_NAME=domofon
      - MQTT_HOST=mqtt
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "8080:8080"
    depends_on:
      - db
      - mqtt
      - redis
    restart: unless-stopped

  client:
    image: golang:1.24.4
    working_dir: /app
    volumes:
      - ./:/app
    command: sh -c "go run ./client/cmd/main.go"
    environment:
      - MQTT_HOST=mqtt
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - mqtt
      - redis
    restart: unless-stopped