// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.865
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "domofonEmulator/client/web/views/layout"

func CreateIntercomePage() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<main>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = CreateIntercomePageStyle().Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<div class=\"title-text\">Добавление нового домофона</div><form hx-encoding=\"multipart/form-data\" hx-post=\"/api/createIntercom\" enctype=\"multipart/form-data\" hx-target=\"#post-result\" hx-target-error=\"#post-result\" hx-trigger=\"submit\" hx-swap=\"innerHTML swap:1s\" hx-on::after-request=\"if(event.detail.successful) this.reset()\"><div class=\"form-group\"><label for=\"mac\">MAC-адрес:</label><div class=\"mac-group\"><input type=\"text\" id=\"mac\" name=\"mac\" placeholder=\"XX:XX:XX:XX:XX:XX\" required> <button type=\"button\" onclick=\"generateMAC()\">Сгенерировать</button></div></div><div class=\"form-group\"><label for=\"address\">Адрес установки:</label> <input type=\"text\" id=\"address\" name=\"address\" required></div><div class=\"form-group\"><label for=\"apartments\">Количество квартир:</label> <input type=\"number\" id=\"apartments\" name=\"apartments\" min=\"1\" required></div><button type=\"submit\">Создать домофон</button></form><div id=\"post-result\"></div></main>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = layout.Layout(layout.LayoutProps{
			Title:           "DomofonPanel",
			MetaDescription: "DomofonPanel",
		}).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func CreateIntercomePageStyle() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var3 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var3 == nil {
			templ_7745c5c3_Var3 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<style>\r\n    body {\r\n        max-width: 600px;\r\n        margin: 0 auto;\r\n        padding: 20px;\r\n\r\n    }\r\n\r\n    .form-group {\r\n        margin-bottom: 15px;\r\n    }\r\n\r\n    label {\r\n        display: block;\r\n        margin-bottom: 5px;\r\n    }\r\n\r\n    .title-text{\r\n        font-size: 36px;\r\n        margin-bottom: 15px;\r\n    }\r\n\r\n    input[type=\"text\"],\r\n    input[type=\"number\"] {\r\n        width: 100%;\r\n        padding: 8px;\r\n        border: 1px solid #ddd;\r\n        border-radius: 4px;\r\n        box-sizing: border-box;\r\n    }\r\n\r\n    button {\r\n        background-color: rgb(59, 59, 59);\r\n        color: white;\r\n        padding: 10px 15px;\r\n        border: none;\r\n        border-radius: 4px;\r\n        cursor: pointer;\r\n        font-size: 16px;\r\n    }\r\n\r\n    button:hover {\r\n        background-color: rgb(68, 68, 68);\r\n    }\r\n\r\n    .mac-group {\r\n        display: flex;\r\n        gap: 10px;\r\n    }\r\n\r\n    .mac-group input {\r\n        flex: 1;\r\n    }\r\n\r\n    .mac-group button {\r\n        width: auto;\r\n    }\r\n</style><script>\r\n    function generateMAC() {\r\n        const hexDigits = \"0123456789ABCDEF\";\r\n        let mac = \"\";\r\n        for (let i = 0; i < 6; i++) {\r\n            mac += hexDigits.charAt(Math.floor(Math.random() * 16));\r\n            mac += hexDigits.charAt(Math.floor(Math.random() * 16));\r\n            if (i < 5) mac += \":\";\r\n        }\r\n        const firstByte = parseInt(mac.substring(0, 2), 16);\r\n        const newFirstByte = (firstByte | 0x02) & 0xFE;\r\n        const newFirstHex = newFirstByte.toString(16).padStart(2, '0').toUpperCase();\r\n        document.getElementById(\"mac\").value = newFirstHex + mac.substring(2);\r\n    }\r\n</script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
